# Generated by Django 3.1.7 on 2021-03-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_arrival_date',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
