# Generated by Django 3.1.7 on 2021-03-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0002_order_estimated_arrival_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='note',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
